name: vorflow
channels:
  - nodefaults
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - gmsh
  - geopandas
  - shapely
  - numpy
  - pandas
  - scipy
  - pyproj
  - pytest
  - jupyter
  - matplotlib
  - pip:
      - -e ..[dev]
